name: task-a cd

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt
      - name: Run tests
        run: |
          pytest ./task_a/task_a.py
